### ISSUE TITLE
这个多久没维护了

### ISSUE THREAD

**Issue by x-wesley** [micro-in-cn/platform-web#22]
我clone下来后   编译不通过

这个项目有什么替代品么？

**Comment by printfcoder** [comment]
可以使用`micro web`指令，项目很久没有维护了，在计划废掉或重新开发，需要在考虑一段时间，看中国站的发展，如果愿意可以一起加入维护。

**Comment by x-wesley** [comment]
> 可以使用`micro web`指令，项目很久没有维护了，在计划废掉或重新开发，需要再考虑一段时间，看中国站的发展，如果愿意可以一起加入维护。

micro web 不能看那些监控信息是吧？
目前也没有什么可以替代的产品么

**Comment by printfcoder** [comment]
不能，监控目前还没有一站式方案，可以参考使用普罗米修斯，然后自行实现exporter，上报自己需要的信息。

**Comment by printfcoder** [comment]
中国站将持续开发platform-web，欢迎关注
