### ISSUE TITLE
micro服务治理相关功能加强

### ISSUE THREAD

**Issue by Eter365** [micro-in-cn/platform-web#23]
## 1. 背景
go-micro 是微服务框架，如果上线以后，那么微服务数量一般情况会稳定增加，大多数创业型公司没有时间从零开始搞服务治理平台， 如果有现成的就直接用了。如果官方有一个基本的管理平台，大多数公司搞个二次开发应该问题不大。

## 2. 现状
治理要有对应的插件欠缺

## 3. 目标
- 简单易用
- 减少故障发现时间
- 降低故障定位成本

### 4.1  服务治理平台
建议初期可以先实现基础服务治理，例如：实时业务指标监控，对于高级功能，例如流量链路监控、熔断限流、弹性伸缩，持续集成... 等，后续逐步添加

### 4.2  服务端监控
官方也建议使用Prometheus等监控方案，后续是否可以考虑深度集成服务端项目基础组件(实时业务指标监控)，提供系统丰富的性能指标、健康状况、实时告警等。

**Comment by printfcoder** [comment]
在去年确实想做这么一个治理平台，后面发现很困难，我们看现在开源出来的作品，基本所有的开源微框架都只做了极小的治理功能，无非就是查看节点，方法调用。

而链路监控、熔断、降级甚至不太相关的CICD都是由其它作品来完成。

如果我们要去做这么一个大而全的平台，从人力时间上看是不可能的。目前能做的也只是站在巨人肩上，比如监控，那只能集成Prometheus+Grafana的方案，一来成熟，二来UI极好，要做的仅是把自己的业务指标映射成Prometheus的风格。

但是都用其它开源工具会造成一个问题，那就是割裂，治理入口不统一，UI混乱。虽然大部分工具都支持LDAP协议，在访问控制上有一定支撑，可这远远不够。

如果我们只做上层集成，那我们要写一堆插件，让服务去集成，然后我们的治理平台就可以去把服务管理起来。比如写监控插件，把业务指标上报到Prometheus，重写UI到PlatformWeb。

但这工作量其实非常大。需要稳定的团队来做，开发难度不亚于一个中型公司的运维研发团队的工作量。

**Comment by printfcoder** [comment]
`micro web` 命令会打开8082端口，目前有基本的查看节点和调用功能，非常初级的能力，远远没有达到治理与监控标准。

@Eter365 有没有兴趣一起先把治理能力做起来？

如此，我们需要

- 节点健康插件，有Go-Micro有Health接口，但过于简单，一个健康插件至少能监控服务及服务自身的组件运动情况，比如能检测服务端口、API、数据库（Connect、Pool等）、Redis、Disk、Mem、Config等。
- 服务治理，上下线、调用、限流等
- 微服务配置中心（在开发，但是需要统一管理UI）
- 流量监控插件

**Comment by Eter365** [comment]
可以的，治理能力的确是一个重要的方向，项目可以慢慢迭代，可以先把架子搭起来。

我这边在项目上正在使用go-micro进行微服务开发，但是目前对go-micro的理解并不太深入。

后面考虑做一个 roadmap ，这个比较重要，可以明确方向。

我这边提供的能力包含：
Go的开发，VUE项目开发、我们团队还在调研flutter。

**Comment by printfcoder** [comment]
@Eter365 OK，加V？我的SLliuxian
